### Практическое задание - Линейная алгебра: Урок 3, 4.

#### Урок 3: Матрицы и матричные операции. Часть 1

1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .

По правилу произведения матриц число столбцов в матрице А должно совпадать с числом строк в матрице В. Следовательно:

а)A  — матрица  4×2 ,  B  — матрица  4×2 
в матрице А число столбцов = 2, а в матрице В число строк = 4, и наоборот, поэтому произведения матриц AB и BA не могут быть определены.

Проверим в Python: 

In [5]:
import numpy as np

In [6]:
def create_matrix(n, m, min_value=0, max_value=9):
    try:
        return np.random.randint(min_value, max_value+1, (n, m))
    except Exception as e:
        return e

def check(A, B):
    try:
        if len(A[0]) == len(B):
            return True
        else:
            return False
    except Exception as e:
        print(f'Exception: {e}')
        return False

In [7]:
A = create_matrix(4, 2)
B = create_matrix(4, 2)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'AB:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц AB не определено.\n')
    
if check(B, A):
    print(f'BA:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц BA не определено.\n')

A:
[[8 6]
 [1 8]
 [1 4]
 [3 7]]

B:
[[7 6]
 [1 7]
 [2 4]
 [8 2]]

Произведение матриц AB не определено.

Произведение матриц BA не определено.



б) A  — матрица  2×5 ,  B  — матрица  5×3 
1. в матрице А число столбцов = 5, в матрице В число строк = 5, произведения матриц AB может быть определено, размерность матрицы AB при этом составит 2х3.
2. в матрице B число столбцов = 3, в матрице А число строк = 2, произведения матриц BA не может быть определено.

Проверим в Python:

In [4]:
A = create_matrix(2, 5)
B = create_matrix(5, 3)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'AB:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц AB не определено.\n')
    
if check(B, A):
    print(f'BA:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц BA не определено.\n')

A:
[[9 7 8 2 3]
 [9 3 5 5 6]]

B:
[[5 9 3]
 [6 1 0]
 [5 6 3]
 [9 1 8]
 [0 5 9]]

AB:
[[145 153  94]
 [133 149 136]]

Произведение матриц BA не определено.



в)  A  — матрица  8×3 ,  B  — матрица  3×8
1. в матрице А число столбцов = 3, в матрице В число строк = 3, произведения матриц AB может быть определено, размерность матрицы AB при этом составит 8х8.
2. в матрице B число столбцов = 8, в матрице А число строк = 8, произведения матриц BA может быть определено, размерность матрицы AB при этом составит 3х3.

Проверим в Python:

In [8]:
A = create_matrix(8, 3)
B = create_matrix(3, 8)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'AB:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц AB не определено.\n')
    
if check(B, A):
    print(f'BA:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц BA не определено.\n')

A:
[[9 4 8]
 [5 0 0]
 [7 9 9]
 [7 6 9]
 [5 3 9]
 [3 5 2]
 [0 6 7]
 [4 6 3]]

B:
[[9 7 7 2 7 7 0 4]
 [4 2 5 0 4 5 1 4]
 [5 9 8 9 8 7 6 7]]

AB:
[[137 143 147  90 143 139  52 108]
 [ 45  35  35  10  35  35   0  20]
 [144 148 166  95 157 157  63 127]
 [132 142 151  95 145 142  60 115]
 [102 122 122  91 119 113  57  95]
 [ 57  49  62  24  57  60  17  46]
 [ 59  75  86  63  80  79  48  73]
 [ 75  67  82  35  76  79  24  61]]

BA:
[[251 191 242]
 [132 128 142]
 [298 283 342]]



г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4
в матрице А и матрице В число строк и столбцов одинаковое и = 4, произведения матриц AB и ВА может быть определено, размерность при этом составит 4х4.

Проверим в Python:

In [9]:
A = create_matrix(4, 4)
B = create_matrix(4, 4)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'AB:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц AB не определено.\n')
    
if check(B, A):
    print(f'BA:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц BA не определено.\n')

A:
[[1 7 6 8]
 [0 9 5 4]
 [3 7 7 5]
 [4 6 1 1]]

B:
[[1 7 2 9]
 [7 0 5 1]
 [9 4 1 2]
 [9 9 4 1]]

AB:
[[176 103  75  36]
 [144  56  66  23]
 [160  94  68  53]
 [ 64  41  43  45]]

BA:
[[ 43 138  64  55]
 [ 26  90  78  82]
 [ 20 118  83  95]
 [ 25 178 128 129]]



2. Найти сумму и произведение матриц  ([1, −2], [3, 0])  и  B=([4, -1], [0, 5])

In [14]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

print(f'A + B:\n{A + B}\n')
print(f'AB:\n{np.dot(A, B)}\n')
print(f'BA:\n{np.dot(B, A)}\n')

A:
[[ 1 -2]
 [ 3  0]]

B:
[[ 4 -1]
 [ 0  5]]

A + B:
[[ 5 -3]
 [ 3  5]]

AB:
[[  4 -11]
 [ 12  -3]]

BA:
[[ 1 -8]
 [15  0]]



3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию  3A−2B+4C  для матриц  A=[[1, 7], [3, -6]] ,  B=[[0, 5], [2, -1]] ,  C=[[2, -4], [1, 1]]).

Для того, чтобы вычислить линейную комбинацию нужно сделать последовательно операции умножения на скаляр:

In [20]:
# 3*A
A = np.array([[1, 7], [3, -6]])
A_3 = 3*np.array([A])
print(f'3*A:\n{A_3}\n')
# 2*B
B = np.array([[0, 5], [2, -1]])
B_2 = 2*np.array([B])
print(f'2*B:\n{B_2}\n')
#4*C
C = np.array([[2, -4], [1, 1]])
C_4 = 4*np.array([C])
print(f'4*C:\n{C_4}\n')

3*A:
[[[  3  21]
  [  9 -18]]]

2*B:
[[[ 0 10]
  [ 4 -2]]]

4*C:
[[[  8 -16]
  [  4   4]]]



Затем найдем комбинацию (LinCom):

In [22]:
LinCom = np.array(A_3-B_2+C_4)
print(f'LinCom:\n{LinCom}\n')

LinCom:
[[[ 11  -5]
  [  9 -12]]]



4. Дана матрица  A= ([[4, 1], [5, -2], [2, 3]]). Вычислить  AAT  и  ATA .

Выполним транспонирование с помощию np.T:

In [23]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'A:\n{A}\n')
print(f'A.T:\n{A.T}\n')

print(f'A x A.T:\n{np.dot(A, A.T)}\n')
print(f'A.T x A:\n{np.dot(A.T, A)}\n')

A:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

A.T:
[[ 4  5  2]
 [ 1 -2  3]]

A x A.T:
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A.T x A:
[[45  0]
 [ 0 14]]



5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [24]:
def generate_array(n, m, min_value=0, max_value=9):
    try:
        return [[np.random.randint(min_value, max_value+1) for _ in range(m)] for _ in range(n)]
    except Exception as e:
        return e

def matrix_product(A, B):
    try:
        C = generate_array(len(A), len(B[0]), 0, 0)
        for i in range(len(A)):  
            for j in range(len(B[0])): 
                for k in range(len(B)): 
                    C[i][j] += A[i][k] * B[k][j]
        return C
    except Exception as e:
        return e

#### Урок 3: Матрицы и матричные операции. Часть 2

1. Вычислить определитель:

In [43]:
import math

In [49]:
# a) [[sinx,cosx]−[cosx,sinx]]
# В квадратной матрице определитель находим как разница произведений элементов матрицы, находящихся по диагонали
x = math.pi / 4
A = np.array([[math.sin(x), -math.cos(x)], [math.cos(x), math.sin(x)]])
print(f'A:\n{A}\n')
det_A = A[0][0]*A[1][1] - A[0][1]*A[1][0]
print(f'Определитель:\n{det_A}\n')

A:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Определитель:
1.0000000000000002



In [50]:
# б) ([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'A:\n{A}\n')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

A:
[[4 2 3]
 [0 5 1]
 [0 0 9]]

Определитель:
180


In [51]:
# в)

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'A:\n{A}\n')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Определитель:
0


2. Определитель матрицы  A  равен  4 . Найти:

а)  det(A^2) ;

б)  det(A^T) ;

в)  det(2A) .

In [58]:
#a) 

A = np.array([[1, -2], [1, 2]])

print(f'A:\n{A}\n')
print(f'det_A: {np.linalg.det(A)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det_A: 4.0



In [59]:
print(f'A^2:\n{np.dot(A, A)}\n')
print(f'det_A^2: {np.linalg.det(np.dot(A, A))}\n')

A^2:
[[-1 -6]
 [ 3  2]]

det_A^2: 16.000000000000007



In [60]:
# б)
print(f'A:\n{A.T}\n')
print(f'det_A.T: {np.linalg.det(A.T)}\n')

A:
[[ 1  1]
 [-2  2]]

det_A.T: 4.0



In [62]:
# в)
print(f'2A:\n{np.dot(2, A)}\n')
print(f'det_2A: {np.linalg.det(2 * A)}\n')

2A:
[[ 2 -4]
 [ 2  4]]

det_2A: 15.999999999999998



3. Доказать, что матрица

[[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

вырожденная.

Матрица является вырожденной если:

1) Если ее определитель равен 0.

2) Если, как минимум, две строки матрицы A линейно зависимы.

In [65]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

print(f'A:\n{A}\n')

print(f'det_A: {np.linalg.det( A)}\n')


A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]

det_A: 0.0



4. Найти ранг матрицы:

In [66]:
# а) 
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

print(f'A:\n{A}\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]



In [70]:
# Первая + вторая строки матрицы A:

print(f'{A[0]} + {A[1]} = {A[0] + A[1]}\n')
print(f'Третья строка матрицы A:')
print(f'{A[2]}\n')

# Третья строка матрицы - это линейная комбинация первой и второй строк

print(f'rank_A: 2\n')

[1 2 3] + [1 1 1] = [2 3 4]

Третья строка матрицы A:
[2 3 4]

rank_A: 2



In [72]:
# б)

A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'A:\n{A}\n')
print(f'{A[2]} - {A[1]} = {A[2] - A[1]}\n')
print(f'{A[0]}\n')
print(f'rank(A): 3\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]

[0 0 4 3] - [0 0 2 2] = [0 0 2 1]

[0 0 2 1]

rank(A): 3

