### Практическое задание - Линейная алгебра: Урок 5.  Линейные преобразования

1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей A = ([[-1, -6], [2, 6]])

In [2]:
import numpy as np

In [11]:
A = np.array([[-1, -6], [2, 6]])
print(f'A:\n{A}\n')

A:
[[-1 -6]
 [ 2  6]]



Собственные значения находим по формуле: det(A-λI) = 0; 

    λ^2-(-1+6)*λ+(-6+12) = λ^2+5λ+6 = 0
    D = b^2 + 4ac = (-5)^2-4*1*6 = 1
    x1 = 2;
    x2 = 3

Проверим в Python:

In [12]:
w, v = np.linalg.eig(A)
print(f'Собственные значения:\n{w}')

Собственные значения:
[2. 3.]


Найдем собственные векторы:
    для λ = 2:
        
    -x1+6x2=2x1
    2x1+6x2=2x2
    
    3x1 = -6x2
    2x1 = -x1
    
    x1 = -2
    x2 = 1
    
    v1 = (-2, 1)
    
    для λ = 3:
        
    -x1+6x2=3x1
    2x1+6x2=3x2
    
    4x1 = -6x2
    2x1 = -3x1
    
    x1 = 3/2
    x2 = -1
    
    v1 = (-2, 1)

Проверим в Python:

In [13]:
w, v = np.linalg.eig(A)
print(f'Собственные векторы:\n{v[:, 0]}, {v[:, 1]}\n')

Собственные векторы:
[-0.89442719  0.4472136 ], [ 0.83205029 -0.5547002 ]



2. Дан оператор поворота на 180 градусов, задаваемый матрицей [[-1, 0], [0, -1]]
Показать, что любой вектор является для него собственным.

In [9]:
A = np.array([[-1, 0], [0, -1]])

print(f'A:\n{A}\n')

A:
[[-1  0]
 [ 0 -1]]



Собственным вектором линейного оператора A является ненулевой вектор x такой, что Ax = λx.
Для единичной матрицы E любой вектор x является собственным, с собственным числом, равным 1, так как Ex = x.
Так как матрица A диагональная, тогда собственные значения: λ1 = -1, λ2 =-1.

Таким образом, любой ненулевой вектор является собственным для линейного оператора A =-1E.

3. Пусть линейный оператор задан матрицей [[1, 1], [-1, 3].
Установить, является ли вектор  x=(1,1)  собственным вектором этого линейного оператора.

[[1, 1], [-1, 3] * [1, 1] = λ * [1, 1]
 
 1+1 = 1*λ
 
-1+3 = 1*λ
 
 λ=2
 λ=2
 
 Следовательно, вектор x=(1,1) является собственным вектором линейного оператора A, а его собственное значение составляет λ=2.

4. Пусть линейный оператор задан матрицей [[0, 3, 0], [3, 0, 0], [0, 0, 3]]. 

Установить, является ли вектор  x=(3,−3,−4)  собственным вектором этого линейного оператора.

In [16]:
print(np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]]))

[[0 3 0]
 [3 0 0]
 [0 0 3]]


[[0, 3, 0], [3, 0, 0], [0, 0, 3] * [3,−3,−4] = λ*[3,−3,−4]
 
 3*λ = -9
 
 -3*λ = 9
 
 -4*λ = -12
 
 λ=3 
 λ=-3
 λ=3

Вектор x=(3, -3, -4) не является собственным вектором линейного оператора A.